version: '{build}'

branches:
  only:
  - master

init:
    - cmd: git config --global core.autocrlf true

artifacts:
  - path: FWTL.Core.Common\nupkgs\*.nupkg
    name: nuget-events

cache:
  - packages -> FWTL.Events.csproj

pull_requests:
  do_not_increment_build_number: true

before_build:
  - cmd: dotnet restore FWTL.sln

build_script:
  - cmd: dotnet build FWTL.sln --no-restore 

after_build:
- ps: >-
    if($env:APPVEYOR_REPO_TAG_NAME)
    {
        dotnet pack FWTL.Events/FWTL.Events.csproj --no-build --output nupkgs -p:PackageVersion=$env:APPVEYOR_REPO_TAG_NAME
    }
nuget:
    disable_publish_on_pr: true
    
deploy: 
    - provider: NuGet
      server: https://fwtlnuget.azurewebsites.net/nuget
      api_key:
          secure: e8azew1tIzD/MZI/okeF195cMFeQTElB+sAX0Vr2/Cc=
      artifact: nuget-events
      on:
          appveyor_repo_tag: true
    
notifications:
- provider: Email
  to:
  - a@gmail.info
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false